---
- hosts: docker_host
  tasks:
  - name: stop and remove image and container
    block:
    - name: stop container
      command: docker stop hello-world-container
    - name: remove container
      command: docker rm hello-world-container
    - name: remove image
      command: docker image rm saria2020/java-hello-world
    ignore_errors: true
  - name: run container
    command: docker run -d --name hello-world-container -p 8080:8080 nobreak01/java-hello-world
