---
- name: Jenkins CI/CD Test Playbook
  hosts: ansible_host
  tasks:
  - name: build docker image with war file
    command: docker build -t my-hello-world .
    args:
      chdir: /home/vagrant/hello-world
  - name: run container with my image
    command: docker run -d --name my-hello-world-container -p 8080:8080 my-hello-world
